site_name: Dr Saeed Parsa Compiler Course
repo_url: https://github.com/parsa-git/compiler_project_refactoring

theme:
  name: material


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Lectures:
        - Lexical analysis: lectures/lexical_analysis.md
        - Grammars and Parsing: lectures/grammars_and_parsing.md
        - Top-down parser: lectures/top_down_parser.md
    - Projects:
      - Factory pattern: projects/design_pattern/factory.md
      - Singleton pattern: projects/design_pattern/singleton.md