site_name: Dr Saeed Parsa Compiler Course


theme:
  name: material


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Factory Pattern: factory.md